spring:
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.format_sql: false
      hibernate.type: info
  datasource:
    url: jdbc:postgresql://localhost:5432/grafana
    driverClassName: org.postgresql.Driver
    username: grafana
    password: grafana

# logging levels

logging.level:
  org.springframework: INFO
